CFILES = src

.PHONY: all
all: ex_6_1 ex_6_2 ex_6_3 ex_6_4 ex_6_5 \
	 ex_6_6 ex_6_7 ex_6_8 ex_6_9 ex_6_10 \
	 ex_6_11 ex_6_12 ex_6_13

ex_6_1: ${CFILES}/ex_6_1.c
	gcc ${CFILES}/ex_6_1.c -o ex_6_1
ex_6_2: ${CFILES}/ex_6_2.c
	gcc ${CFILES}/ex_6_2.c -o ex_6_2
ex_6_3: ${CFILES}/ex_6_3.c
	gcc ${CFILES}/ex_6_3.c -o ex_6_3
ex_6_4: ${CFILES}/ex_6_4.c
	gcc ${CFILES}/ex_6_4.c -o ex_6_4
ex_6_6: ${CFILES}/ex_6_5.c
	gcc ${CFILES}/ex_6_5.c -o ex_6_5
ex_6_6: ${CFILES}/ex_6_6.c
	gcc ${CFILES}/ex_6_6.c -o ex_6_6
ex_6_7: ${CFILES}/ex_6_7.c
	gcc ${CFILES}/ex_6_7.c -o ex_6_7
ex_6_8: ${CFILES}/ex_6_8.c
	gcc ${CFILES}/ex_6_8.c -o ex_6_8
ex_6_9: ${CFILES}/ex_6_9.c
	gcc ${CFILES}/ex_6_9.c -lm -o ex_6_9
ex_6_10: ${CFILES}/ex_6_10.c
	gcc ${CFILES}/ex_6_10.c -o ex_6_10
ex_6_11: ${CFILES}/ex_6_11.c
	gcc ${CFILES}/ex_6_11.c -o ex_6_11
ex_6_12: ${CFILES}/ex_6_12.c
	gcc ${CFILES}/ex_6_12.c -o ex_6_12
ex_6_13: ${CFILES}/ex_6_13.c
	gcc ${CFILES}/ex_6_13.c -o ex_6_13

clean:
	rm ex_6_1 ex_6_2 ex_6_3 ex_6_4 ex_6_5 \
	   ex_6_6 ex_6_7 ex_6_8 ex_6_9 ex_6_10 \
	   ex_6_11 ex_6_12 ex_6_13
